# Generated by Django 3.1.7 on 2021-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('courier_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер курьера')),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=32, verbose_name='Тип передвижения')),
                ('regions', models.JSONField(default=list)),
                ('working_hours', models.JSONField(default=list)),
                ('earnings', models.PositiveIntegerField(default=0, verbose_name='Заработок курьера')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
    ]
