# Generated by Django 3.1.7 on 2021-03-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Вес заказа')),
                ('region', models.PositiveIntegerField(blank=True, null=True, verbose_name='Регион')),
                ('delivery_hours', models.JSONField(default=list, verbose_name='Часы работы')),
                ('time_of_delivered', models.DateTimeField(blank=True, null=True, verbose_name='ДТ доставки')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлено?')),
                ('courier_type', models.CharField(blank=True, choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=32, null=True, verbose_name='Тип курьера')),
                ('time_of_assign', models.DateTimeField(blank=True, null=True, verbose_name='ДТ принятия заказа в работу')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app_couriers.couriers', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
